[package]
name = "Ass5_Rocket_iot"
version = "0.1.0"
authors = ["shahzaib sohail <shahzaibsohail0077@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5" 
